#!/usr/bin/env php
<?php

/*
* ------------------------------------
* Load all third party modules
* install buy composer package manager
* ------------------------------------
*/ 
require __DIR__."/vendor/autoload.php";


/*
* -----------------------------------------------------
* Include App class
* -----------------------------------------------------
*/ 
require __DIR__."/configs/App.php";


/*
|----------------------------------------------
| Importing Console class namespace for usage
| Contains all modules and classes for cli usages
|----------------------------------------------
|
*/
use App\Core\Console\Console;


/*
|----------------------------------------------
| Initializing the console app
|----------------------------------------------
| @param $argv - the command line arguments
|
*/

$console = new Console(
    new App\Core\Server, $argv
);

/*
|----------------------------------------------
| Run the Console Application
|----------------------------------------------
|
| ALl command run on the cli will be handle and 
| response will be sent back to the terminal
|
*/

$console->run();
