#!/usr/bin/env php
<?php

require __DIR__.'/Core/autoload_console.php';

use Console\Console;
use App\Core\Server;

/*
* -----------------------------------------------------
* Initialize App Server
* -----------------------------------------------------
*/ 

$server = new Server($debug = true);

/*
* -----------------------------------------------------
* Server will be initialized and modules will be loaded
* using the load modules function from the server
* -----------------------------------------------------
*/ 

$server->load_modules($modules);

/*
|----------------------------------------------
| Initializing the console app
|----------------------------------------------
| @param $argv - the command line arguments
|
*/

$console = new Console($argv);

/*
|----------------------------------------------
| Run the Console Application
|----------------------------------------------
|
| ALl command run on the cli will be handle and 
| response will be sent back to the terminal
|
*/

$console->run();
